// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cetgzusfudtwiftiinie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNldGd6dXNmdWR0d2lmdGlpbmllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTg0ODQsImV4cCI6MjA2ODc3NDQ4NH0.n8fO0MyGJOlGnhMh-yzIQ7A62JAk9Vf8YPjrJUqxKVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});